// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MFG.Data;

#nullable disable

namespace MFG.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408100145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MFG.Domain.Entities.ArenaPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("BestWinStreak")
                        .HasColumnType("int")
                        .HasColumnName("best_win_streak");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentTier")
                        .HasColumnType("int")
                        .HasColumnName("current_tier");

                    b.Property<int>("CurrentWinStreak")
                        .HasColumnType("int")
                        .HasColumnName("current_win_streak");

                    b.Property<DateOnly>("LastResetDate")
                        .HasColumnType("date")
                        .HasColumnName("last_reset_date");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("season_id");

                    b.Property<DateTime>("SeasonStartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("season_start_time");

                    b.Property<int>("TotalDefeats")
                        .HasColumnType("int")
                        .HasColumnName("total_defeats");

                    b.Property<int>("TotalVictories")
                        .HasColumnType("int")
                        .HasColumnName("total_victories");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedFreeEntries")
                        .HasColumnType("int")
                        .HasColumnName("used_free_entries");

                    b.HasKey("Id")
                        .HasName("pk_arena_players");

                    b.HasAlternateKey("PlayerId")
                        .HasName("ak_arena_players_player_id");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_arena_players_player_id");

                    b.ToTable("arena_players", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.ArenaRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVictory")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_victory");

                    b.Property<long>("OpponentCp")
                        .HasColumnType("bigint")
                        .HasColumnName("opponent_cp");

                    b.Property<string>("OpponentJob")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("opponent_job");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("opponent_name");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("RatingChange")
                        .HasColumnType("int")
                        .HasColumnName("rating_change");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_arena_records");

                    b.HasIndex("PlayerId", "CreatedAt")
                        .HasDatabaseName("ix_arena_records_player_id_created_at");

                    b.ToTable("arena_records", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CheckDate")
                        .HasColumnType("date")
                        .HasColumnName("check_date");

                    b.Property<int>("ConsecutiveDays")
                        .HasColumnType("int")
                        .HasColumnName("consecutive_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("int")
                        .HasColumnName("reward_amount");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("reward_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attendance_records");

                    b.HasIndex("PlayerId", "CheckDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_records_player_id_check_date");

                    b.ToTable("attendance_records", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("PlayerId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_player_id_type");

                    b.ToTable("currencies", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.CurrencyTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("currency_type");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("reference_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_currency_transactions");

                    b.HasIndex("PlayerId", "CreatedAt")
                        .HasDatabaseName("ix_currency_transactions_player_id_created_at");

                    b.ToTable("currency_transactions", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.GachaHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PityCount")
                        .HasColumnType("int")
                        .HasColumnName("pity_count");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("pool_type");

                    b.Property<string>("ResultGrade")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("result_grade");

                    b.Property<string>("ResultItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("result_item_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gacha_histories");

                    b.HasIndex("PlayerId", "CreatedAt")
                        .HasDatabaseName("ix_gacha_histories_player_id_created_at");

                    b.ToTable("gacha_histories", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.GachaPity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("PoolType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("pool_type");

                    b.Property<int>("TotalPulls")
                        .HasColumnType("int")
                        .HasColumnName("total_pulls");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gacha_pities");

                    b.HasIndex("PlayerId", "PoolType")
                        .IsUnique()
                        .HasDatabaseName("ix_gacha_pities_player_id_pool_type");

                    b.ToTable("gacha_pities", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.Guild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("BossHpRemaining")
                        .HasColumnType("bigint")
                        .HasColumnName("boss_hp_remaining");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Exp")
                        .HasColumnType("int")
                        .HasColumnName("exp");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("guild_name");

                    b.Property<bool>("IsBossDefeated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_boss_defeated");

                    b.Property<string>("LastBossResetDate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("last_boss_reset_date");

                    b.Property<long>("LeaderId")
                        .HasColumnType("bigint")
                        .HasColumnName("leader_id");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.HasIndex("GuildName")
                        .IsUnique()
                        .HasDatabaseName("ix_guilds_guild_name");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.GuildMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("BossAttemptsThisWeek")
                        .HasColumnType("int")
                        .HasColumnName("boss_attempts_this_week");

                    b.Property<long>("BossTotalDamage")
                        .HasColumnType("bigint")
                        .HasColumnName("boss_total_damage");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("GoldDonateCount")
                        .HasColumnType("int")
                        .HasColumnName("gold_donate_count");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<string>("LastDonateResetDate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("last_donate_reset_date");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<bool>("RaidUsedThisWeek")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("raid_used_this_week");

                    b.Property<int>("RubyDonateCount")
                        .HasColumnType("int")
                        .HasColumnName("ruby_donate_count");

                    b.Property<int>("TicketDonateCount")
                        .HasColumnType("int")
                        .HasColumnName("ticket_donate_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guild_members");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_guild_members_guild_id");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_guild_members_player_id");

                    b.ToTable("guild_members", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.IapReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_valid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("platform");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("product_id");

                    b.Property<string>("ReceiptHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("receipt_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_iap_receipts");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_iap_receipts_player_id");

                    b.HasIndex("ReceiptHash")
                        .IsUnique()
                        .HasDatabaseName("ix_iap_receipts_receipt_hash");

                    b.ToTable("iap_receipts", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CombatPower")
                        .HasColumnType("bigint")
                        .HasColumnName("combat_power");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentFloor")
                        .HasColumnType("int")
                        .HasColumnName("current_floor");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint")
                        .HasColumnName("exp");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("job_id");

                    b.Property<int>("JobTier")
                        .HasColumnType("int")
                        .HasColumnName("job_tier");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LastLogoutAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_logout_at");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("MaxFloor")
                        .HasColumnType("int")
                        .HasColumnName("max_floor");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("nickname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("ix_players_firebase_uid");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.ProgressData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("SaveJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("save_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_progress_data");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_progress_data_player_id");

                    b.ToTable("progress_data", (string)null);
                });

            modelBuilder.Entity("MFG.Domain.Entities.ArenaPlayer", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithOne("ArenaPlayer")
                        .HasForeignKey("MFG.Domain.Entities.ArenaPlayer", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arena_players_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.ArenaRecord", b =>
                {
                    b.HasOne("MFG.Domain.Entities.ArenaPlayer", "ArenaPlayer")
                        .WithMany("Records")
                        .HasForeignKey("PlayerId")
                        .HasPrincipalKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arena_records_arena_players_player_id");

                    b.Navigation("ArenaPlayer");
                });

            modelBuilder.Entity("MFG.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_records_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.Currency", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithMany("Currencies")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currencies_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.CurrencyTransaction", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currency_transactions_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.GachaHistory", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithMany("GachaHistories")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_histories_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.GachaPity", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithMany("GachaPities")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pities_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.GuildMember", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_members_guilds_guild_id");

                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithOne("GuildMember")
                        .HasForeignKey("MFG.Domain.Entities.GuildMember", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_members_players_player_id");

                    b.Navigation("Guild");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.IapReceipt", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithMany("IapReceipts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_iap_receipts_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.ProgressData", b =>
                {
                    b.HasOne("MFG.Domain.Entities.Player", "Player")
                        .WithOne("ProgressData")
                        .HasForeignKey("MFG.Domain.Entities.ProgressData", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_data_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MFG.Domain.Entities.ArenaPlayer", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("MFG.Domain.Entities.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("MFG.Domain.Entities.Player", b =>
                {
                    b.Navigation("ArenaPlayer");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("Currencies");

                    b.Navigation("GachaHistories");

                    b.Navigation("GachaPities");

                    b.Navigation("GuildMember");

                    b.Navigation("IapReceipts");

                    b.Navigation("ProgressData");
                });
#pragma warning restore 612, 618
        }
    }
}
